### ISSUE TITLE
Rails/ActiveRecord 7 Support

### ISSUE THREAD

**Issue by ryanwood** [iiwo/easy_tags#42]
Are there any specific reasons why we can't bump the `activerecord` and `activesupport` dependency to support Rails 7?

Currently, it's:
```
  spec.add_runtime_dependency 'activerecord', '>= 5.0', '< 6.2'
  spec.add_runtime_dependency 'activesupport', '>= 5.0', '< 6.2'
```

**Comment by iiwo** [comment]
👍 seems fine, I don't think there are any breaking changes

**Comment by iiwo** [comment]
resolved with https://github.com/iiwo/easy_tags/pull/44
